cloud:
  aws:
    credentials:
      accessKey: AKIA3ZPQJZNV5HYBTCBV
      secretKey: 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
    s3:
      bucket: ishadow-video-directory
    region:
      static: ap-northeast-2
    stack:
      auto: false

ses:
  email: hr.seongeun@gmail.com
  access-key: AKIAJKTMKM4CXTVZXKSA
  secret-key: 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